import React from 'react'
import Footer from '../Footer'

export default function Kvkk() {
    return (
        <div>
           <p>KVKK Kişisel Verilerin Korunmasına İlişkin Bilgilendirme; My Love Butik A.Ş. olarak kişisel verilerinizin 6698 sayılı Kişisel Verilerin Korunması Kanunu'na ("Kanun") uygun olarak işlenerek, muhafaza edilmesine büyük önem veriyoruz. Müşterilerimizi kişisel verileri toplama, işleme, aktarma amacımız ve yöntemlerimiz ve buna bağlı olarak sizlerin Kanun'dan kaynaklanan haklarınızla ilgili bilgilendirmek isteriz.

1. Kişisel verilerin toplanmasına ilişkin yöntemler My Love Butik A.Ş. olarak, veri sorumlusu sıfatıyla, mevzuattan kaynaklanan yasal yükümlülüklerimiz çerçevesinde; markalarımızın hizmetlerinden faydalanabilmeniz, onayınız halinde kampanyalarımız hakkında sizleri bilgilendirmek, öneri ve şikayetlerinizi kayıt altına alabilmek, sizlere daha iyi hizmet standartları oluşturabilmek, My Love Butik A.Ş. ticari ve iş stratejilerinin belirlenmesi ve uygulanması gibi amaçlarla kişisel verilerinizi sözlü, internet sitesi, sosyal medya mecraları, mobil uygulamalar ve benzeri vasıtalarla sözlü, yazılı ya da elektronik yöntemlerle toplamaktayız. Kişisel Verilerin Korunması Kanunu yürürlüğe girmeden önce yasalara uygun şekilde elde edilen kişisel verileriniz de bu belgede düzenlenen şart ve koşullara göre işlenmekte ve korunmaktadır. 2. Kişisel verilerin işlenmesi ve işleme amaçları My Love Butik A.Ş. olarak, veri sorumlusu sıfatı ile çağrı merkezlerimiz, yazılı iletişim kanallarımız, sosyal medya sayfalarımız, mobil iletişim kanalları, mağaza içi iletişim kanalları ve/veya bunlarla sınırlı olmamak üzere her türlü kanallar aracılığı ile; onayınız dahilinde elde ettiğimiz kişisel ve/veya özel nitelikli kişisel verileriniz tamamen veya kısmen elde edilebilir, kaydedilebilir, saklanabilir, depolanabilir, değiştirilebilir, güncellenebilir, periyodik olarak kontrol edilebilir, yeniden düzenlenebilir, sınıflandırılabilir, işlendikleri amaç için gerekli olan ya da ilgili kanunda öngörülen süre kadar muhafaza edilebilir, kanuni ya da hizmete bağlı fiili gereklilikler halinde My Love Butik A.Ş 'nın birlikte çalıştığı özel-tüzel kişilerle ya da kanunen yükümlü olduğu kamu kurum ve kuruluşlarıyla ve/veya Türkiye'de veya yurt dışında mukim olan ilgili 3. kişi gerçek kişi/tüzel kişilerle paylaşılabilir/devredilebilir, kanuni ya da hizmete bağlı fiili gereklilikler halinde yurtdışına aktarılabilir. My Love Butik A.Ş. müşterilerinin markalarımızın hizmetlerinden faydalanabilmesi, onayınız halinde kampanyalarımız hakkında sizleri bilgilendirmek, öneri ve şikayetlerinizi kayıt altına alabilmek, sizlere daha iyi hizmet standartları oluşturabilmek, My Love Butik A.Ş. ticari ve iş stratejilerinin belirlenmesi ve uygulanması gibi amaçlarla ve her halükarda 6698 sayılı Kişisel Verilerin Korunması Kanunu ve ilgili mevzuata uygun olarak kişisel verilerinizi işleyebileceğimizi bilginize sunarız.
3. Kişisel Verilerin Aktarılması My Love Butik A.Ş. , söz konusu kişisel verilerinizi sadece; açık rızanıza istinaden veya Kanun'da belirtilen güvenlik ve gizlilik esasları çerçevesinde yeterli önlemler alınmak kaydıyla yurt içinde ve gerekli güvenlik önlemlerinin alınması kaydıyla yurt dışında, Şirket faaliyetlerinin yürütülmesi veri sahipleri ile müşterilerimiz arasındaki iş ilişkisinin sağlanması ve/veya bu amaçla görüşmeler yapılması, hizmetler, fırsat ve olanaklar sunulması ve hizmet kalitesinin artırılması amacıyla; grup şirketlerimiz, iş ortaklarımız, faaliyetlerimizin gereği anlaşmalı olduğumuz ve hizmet sunduğumuz müşteriler, tedarikçiler, denetim şirketleri veya yasal bir zorunluluk gereği bu verileri talep etmeye yetkili olan kamu kurum veya kuruluşları, bunlarla sınırlı olmamak üzere ilgili diğer otoriteler ile paylaşabilecektir. 4. Kişisel Veri Sahibinin KVK Kanunu'nun ("Kanun") 11. maddesinde Sayılan Hakları My Love Butik A.Ş. ilgili kişilerin aşağıdaki taleplerine karşılık verecektir: My Love Butik A.Ş. 'nın kendilerine ilişkin kişisel verileri işleyip işlemediğini ve hangi kişisel verileri işlediğini öğrenme, İşleme faaliyetinin amaçlarına ilişkin bilgi alma, My Love Butik A.Ş. 'nın yurt içinde veya yurt dışında kişisel verileri aktardığı üçüncü kişileri bilme, Kişisel verilerin eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme, Kanun'a uygun olarak kişisel verilerin silinmesini veya yok edilmesini isteme, Kişisel verilerin düzeltilmesi, silinmesi ya da yok edilmesi talebi halinde; yapılan işlemlerin, kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, İşlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle kişinin kendisi aleyhine bir sonucun ortaya çıkmasına itiraz etme ve kişisel verilerin birer kopyasını alma. Çerez Kullanımı Çerezler, sitemizi ziyaret ettiğinizde bilgisayarınız ya da mobil cihazınıza (akıllı telefon veya tablet gibi) kaydedilen küçük metin dosyaları ya da bilgilerdir. Çerezleri, Sitelerimizin daha kolay kullanılması ve sizin ilgi ve ihtiyaçlarınıza göre ayarlanması için kullanıyoruz. İnternet siteleri bu çerez dosyaları okuyup yazabiliyorlar ve bu sayede tanınmanız ve size daha uygun bir internet sitesi sunulması amacıyla sizinle ilgili önemli bilgilerin hatırlanması sağlanıyor (tercih ayarlarınızın hatırlanması gibi). Çerezler ayrıca, Sitelerimiz üzerinde gelecekteki hareketlerinizin hızlanmasına da yardımcı olur. Bunlara ek olarak, ziyaretçilerin Sitelerimizi nasıl kullandığını anlamak ve Sitelerimizin tasarımını ve kullanışlılığını geliştirmek amacıyla çerezleri Sitelerimizin kullanımı hakkında istatistiksel bilgiler toplamak için de kullanabiliriz.</p>
        <Footer></Footer>
        </div>
        
    )
}
